services:
  - type: web
    name: retell-ai-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      # Add your other environment variables in the Render dashboard after deploy 